name: Deliver Beta release

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_NUMBER: ${{ github.run_id }}
  IS_CI_BUILD: true
  IS_NIGHTLY: false

jobs:
  setup_java:
    name: Setup JAVA 11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

  gradle_build:
    name: Gradle build!
    runs-on: ubuntu-latest
    needs: [ setup_java ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Gradle build
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: 'gradle'
        run: ./gradlew build --no-daemon

  gradle_check:
    name: Gradle Check
    runs-on: ubuntu-latest
    needs: [ gradle_build ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Gradle app check
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: 'gradle'
        run: ./gradlew check

  unit_tests:
    name: run unit tests
    runs-on: ubuntu-latest
    needs: [ gradle_build, gradle_check ]
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: 'gradle'
        run: ./gradlew test

  android_tests:
    name: run android tests
    runs-on:  macos-latest
    needs: [ gradle_build, gradle_check ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          script: ./gradlew connectedCheck

  deploy_beta:
    name: Build Beta apk based on latest push
    runs-on: ubuntu-latest
    needs: [ unit_tests, android_tests ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Debug APK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: 'gradle'
        run: ./gradlew assembleDebug
      - name: Upload APK to workspace
        uses: actions/upload-artifact@v2
        with:
          name: betaAPK
          path: app/build/outputs/apk/debug/app-debug.apk
  telegram_upload:
    name: Upload Beta apk in telegram
    runs-on: ubuntu-latest
    needs: [ deploy_beta ]
    steps:
      - name: Download Beta APK
        uses: actions/download-artifact@v2
        with:
          name: betaAPK
      - name: Send beta build to telegram channel
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHANNEL_CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            #beta build based on pull request on master branch:
            run ID: ${{ github.run_id }}
            Triggered by: ${{ github.actor }}
            Ref: ${{ github.ref }}
            Commit SHA: ${{ github.sha }}
            latest commit description: ${{ github.event.head_commit.message }}
          document: app-debug.apk
      - name: Send confirmation to group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            Sucsses push run!
            additional info:
            run ID: ${{ github.run_id }}
            Triggered by: ${{ github.actor }}
            Ref: ${{ github.ref }}
            Commit SHA: ${{ github.sha }}
            latest commit description: ${{ github.event.head_commit.message }}
            Beta builds available at: @phoenixBrowserChannel